# Generated by Django 5.2.14 on 2026-05-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemmatch'),
        ('messaging', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.itemmatch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('claim_submitted', 'Claim submitted'), ('claim_approved', 'Claim approved'), ('claim_rejected', 'Claim rejected'), ('match_suggested', 'Match suggested')], max_length=40),
        ),
    ]
