# Generated by Django 5.2.14 on 2026-05-30 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_claim_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('viewed', 'Viewed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('match_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='items.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='items.item')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_item_match_pair')],
            },
        ),
    ]
